<a href="https://colab.research.google.com/github/alexnodejs/bandit/blob/main/HT_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [3]:
even = np.arange(30, 71, 2)
even

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [4]:
arr_10 = np.random.randint(0, 1, 10)
arr_10

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [7]:
n = 4
arr_x2 = np.random.randint(1, 10, (n+2, n+2))
arr_x2

a = np.hstack((np.zeros((arr_x2.shape[0], 1)), arr_x2, np.zeros((arr_x2.shape[0], 1))))
array = np.vstack((np.zeros((1, a.shape[1])), a, np.zeros((1, a.shape[1]))))
array

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 8., 6., 2., 5., 6., 8., 0.],
       [0., 8., 5., 2., 8., 6., 5., 0.],
       [0., 6., 1., 8., 9., 1., 3., 0.],
       [0., 5., 4., 7., 8., 8., 5., 0.],
       [0., 5., 5., 4., 5., 9., 6., 0.],
       [0., 8., 2., 5., 4., 1., 6., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [8]:
print('Before Type:', array.dtype)
array_updated_type = array.astype(np.int32, copy=False)
print(array_updated_type)
print('After Type:', array.dtype)

Before Type: float64
[[0 0 0 0 0 0 0 0]
 [0 8 6 2 5 6 8 0]
 [0 8 5 2 8 6 5 0]
 [0 6 1 8 9 1 3 0]
 [0 5 4 7 8 8 5 0]
 [0 5 5 4 5 9 6 0]
 [0 8 2 5 4 1 6 0]
 [0 0 0 0 0 0 0 0]]
After Type: float64


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [11]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 2

x_replaced = np.where(x == var, -1, np.where(x > var, -1, -1))
x_replaced

array([-1, -1, -1, -1, -1, -1, -1, -1])

#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [13]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])
X[np.isnan(X)] = -1

X

array([[ 1.,  2., -1.,  4.],
       [ 5., -1., -1.,  4.],
       [-1., 10., 11., -1.]])

#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [15]:
import numpy as np
X = np.random.rand(4, 6)
X.reshape((3, 8))

array([[0.56898625, 0.53051343, 0.83146404, 0.65279329, 0.0514913 ,
        0.95819168, 0.34912693, 0.90561939],
       [0.45838548, 0.52532658, 0.23770117, 0.33379321, 0.14194338,
        0.57851496, 0.20186859, 0.81921037],
       [0.80167249, 0.83183446, 0.29600944, 0.4843801 , 0.37292398,
        0.24272196, 0.22138861, 0.52177939]])

#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [16]:

arr_3_4 = np.random.rand(3, 4)
arr_3_4

mean_per_column = np.mean(arr_3_4, axis=0)
mean_per_column

array([0.6874587 , 0.38994093, 0.32841983, 0.78717317])

#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [17]:
import numpy as np

matrix = np.random.random((5, 6))

matrix_rounded = np.around(matrix, decimals=1)
sorted_matrix = matrix_rounded[:, matrix_rounded[0, :].argsort()]
sorted_matrix


array([[0.3, 0.4, 0.5, 0.5, 0.7, 0.8],
       [0.4, 0.3, 0.6, 0.9, 0.4, 0.4],
       [0.1, 0.8, 0.3, 0.1, 0.9, 0.4],
       [0.9, 0.7, 0.6, 0.7, 0.3, 0.2],
       [0.3, 0.1, 0. , 0.1, 0.2, 0. ]])

#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [20]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])
X[(3 < X) & (X < 6 )]

array([4, 5, 5, 4])

#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [22]:
X = np.random.random((5, 6))

X_normalized = (X  - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

print(X_normalized)

[[0.16067554 0.         1.         0.10315306 0.30089204 0.        ]
 [1.         0.73811461 0.92092894 0.51416343 0.03990278 1.        ]
 [0.53667119 1.         0.78179652 0.9802976  1.         0.34301292]
 [0.         0.46815161 0.6384397  0.         0.29377965 0.41969642]
 [0.46659774 0.08300564 0.         1.         0.         0.83355477]]
